CREATE DATABASE IF NOT EXISTS email_first;

USE email_first;

CREATE TABLE email2uid (
    email VARCHAR(32) NOT NULL,
    uid BIGINT(20) NOT NULL,
    PRIMARY KEY (email)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
