CREATE DATABASE IF NOT EXISTS gacc;

USE gacc;

CREATE TABLE email2uid (
    email VARCHAR(32) NOT NULL,
    uid BIGINT(20) NOT NULL,
    PRIMARY KEY (email)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
