CREATE DATABASE IF NOT EXISTS gacc;

USE gacc;

CREATE TABLE phone2uid (
    phone BIGINT(20) NOT NULL,
    uid BIGINT(20) NOT NULL,
    PRIMARY KEY (phone)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
