CREATE DATABASE IF NOT EXISTS gacc;

USE gacc;

CREATE TABLE uid2cellphone (
    uid BIGINT(20) NOT NULL,
    cellphone CHAR(15) NOT NULL,
    verified TINYINT(4) NOT NULL,
    createtime DATETIME NOT NULL,
    PRIMARY KEY (uid)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
