CREATE DATABASE IF NOT EXISTS genuid;

USE genuid;

CREATE TABLE uid_slice (
    uid BIGINT(20) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (uid)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
INSERT INTO uid_slice (uid) VALUES (10000000);
