CREATE DATABASE IF NOT EXISTS gacc;

USE gacc;

CREATE TABLE user_secinfo(
    uid BIGINT(20) NOT NULL,
    passwd CHAR(32) NOT NULL,
    createtime DATETIME NOT NULL,
    PRIMARY KEY (uid)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
